project:
  type: website
  output-dir: _site

website:
  title: "ToTaL Engineering"
  navbar:
    title: false
    search: true
    logo: graphics/Banner.png
    logo-href: http://buffalobadger.github.io
    left:
      - text: "Reaction Engineering Basics"
        href: http://buffalobadger.github.io/RE_Basics
      - text: "SCoRE"
        href: http://buffalobadger.github.io/SCoRE
      - text: "ToTaL Engineering"
        href: index.qmd
      - text: "The Sett"
        href: http://buffalobadger.github.io/The_Sett
      - text: "About"
        href: http://buffalobadger.github.io/about.html  
  search:
    location: navbar
    type: overlay
  page-footer:
    background: light
    right: 
      - text: Copyright 2024, Carl Lund 
  favicon: graphics/BuffaloBadger_16_16.png
  sidebar:
    style: floating
    search: false
    collapse-level: 1
    contents: 
      - text: "Welcome"
        href: index.qmd
      - section: "A Problem-Solving Course"
        href: about_react_eng.qmd
        contents: 
          - text: "The Early Years"
            href: early_years.qmd
      - section: "A Discussion Course"
        href: about_energy_environment.qmd
        contents:
          - text: "The Initial Offering"
            href: initial_offering.qmd
      - text: "Archive"
        href: total_ps.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
