---
bibliography: references.bib
csl: ieee-with-url.csl
---

{{< include includes/_top_logo.qmd >}}

## Energy and the Environment: A Discussion Course {.ch}

This course is an elective course in the chemical engineering curriculum. It is a relatively new course that I believe was first offered online during the COVID-19 pandemic. The 
professor who developed has left the department, having last offered the course in Spring 2021. I was assigned to teach it this semester (Spring 2024). It is dual-listed at both the undergraduate and graduate levels with the expectation that those taking the graduate version will delve more deeply into the subject. The catalog description is as follows:

> Global and multidisciplinary perspective needed to understand challenges associated with electricity production and energy options. Environmental principles relevant to: energy perspectives worldwide, low-carbon technologies, energy efficiency, biomass, hydrogen economy, fuel cells, carbon capture and storage, and energy policy and regulation.

The course carries three credits. It meets for 80 minutes, twice a week over a span of 15 weeks (with one week off for mid-semester break). Undergraduates who take the course are typically seniors in their final semester. Graduate students who take it are typically in their first or second year of graduate studies. Most, but not all, of the students who take the course are in chemical engineering.

## License {.ch}

{{< include includes/_bottom_license.qmd >}}
