---
bibliography: references.bib
csl: ieee-with-url.csl
---

{{< include includes/_top_logo.qmd >}}

## Kinetics and Reaction Engineering: A Problem-Solving Course {.ch}

This course is a required, undergraduate course on chemical kinetics and chemical reactor design. In this course, I present theories, derive and simplify equations, and show how to use the theory and equations to answer questions about the performance or behavior of some reactive process or system. The learning outcomes center around the learner being able to formulate and solve equations to answer similar questions about systems or processes to which the theory applies. The questions typically take the form of “story problems” that consist of a written paragraph or two that provide some information and then ask one or more questions. As such, I consider it to be a prototypical engineering problem-solving course.

The class has always carried three credits, and it has always been offered in the fall semester only. It meets for fifty minutes, three times per week over the course of 14 to 15 weeks, with a three-hour final exam period scheduled a few days to a week after classes end. Prior to the fall of 2008 it was listed in the fourth year of the four-year chemical engineering curriculum, and most of those enrolled were seniors. In fall of 2008 the curriculum was revised, and it was listed in the third year. However, students can delay taking it until their senior year without delaying their graduation. As a consequence, since 2008 a mix of juniors and seniors have typically enrolled in the course.

Broadly, students learn to solve five types of problems in the course: rate expression generation, kinetics data analysis, isolated reactor modeling, reactor systems modeling and non-ideal reactor modeling. The same sets of equations are used in kinetics data analysis, isolated reactor modeling and reactor system modeling, but the manner in which they are used differs. The nature of the problems ranges from calculating response (one correct answer) through optimization (multiple "correct" answers) to design (partially specified problem with multiple "correct" answers).

There are three pre-requisite courses and one co-requisite course. One pre-requisite is a course on material and energy balances. The equations that are most often used in reaction engineering are derived from material and energy balances. The second pre-requisite is a course on differential equations. A large fraction of reaction engineering problems require the solution of differential equations, but in reaction engineering those equations are solved numerically. This is the reason for the co-requisite course which is about numerical methods. The final pre-requisite course is chemical thermodynamics. Many of the terms appearing in reaction engineering equations have thermodynamic origins.

## License {.ch}

{{< include includes/_bottom_license.qmd >}}
